# 🐍 Python Data Structures — Practice Worksheet
### 18 Tasks covering Numbers, Booleans, Strings, Loops, Lists, Tuples, Dictionaries, Sets, NumPy & Pandas

---

> 📌 **Instructions**
> - Complete **all 18 tasks** from top to bottom — each builds on previous concepts.
> - Fill in every `# YOUR CODE HERE` block. Do **not** change task descriptions.
> - Run each cell after completing it to verify your output.
> - Expected outputs are shown where helpful.

---


## ⚙️ Setup — Run This Cell First


In [1]:
!pip install numpy 

In [2]:
!pip install pandas 

  Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
 

In [3]:
!pip install scikit-learn


In [4]:
import random
import collections
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
print("All libraries imported successfully ✅")


All libraries imported successfully ✅


---
# 🔢 Section 1 — Primitive Data Types


## 📝 Task 1 — Numbers & Arithmetic

### Background
Python supports two main numeric types: `int` (whole numbers) and `float` (decimals). You can use the standard arithmetic operators: `+`, `-`, `*`, `/`, `//` (floor division), `%` (modulo), `**` (exponentiation).

### 🎯 Your Task
Given `a = 17` and `b = 5`, compute and **print** each of the following with a descriptive label:

| Expression | Expected Output |
|---|---|
| `a + b` | 22 |
| `a - b` | 12 |
| `a * b` | 85 |
| `a / b` | 3.4 |
| `a // b` | 3 |
| `a % b` | 2 |
| `a ** b` | 1419857 |

Then print the **type** of `a` and the **type** of `a / b` and explain (in a comment) why they differ.

> 💡 **Hint:** Use `print(f"a + b = {a + b}")` for clean labelled output. Use `type()` to check types.


In [ ]:
a = 17
b = 5

# YOUR CODE HERE
# Print all 7 arithmetic results with labels
x=a+b
print("a + b =", x)
x=a-b
print("a - b =", x)
x=a*b
print("a * b =", x)
x=a/b
print("a / b =", x)
x=a**b
print("a ** b =", x)
x=a%b
print("a % b =", x)

# Print type of a
print(type(a))

# Print type of a / b
print(type(a/b))

# Comment: why is the type of a/b different from the type of a?
# Answer: The type of a/b is float, while the type of a is int. This is because division of two integers in Python 3 returns a float.


a + b = 22
a - b = 12
a * b = 85
a / b = 3.4
a ** b = 1419857
a % b = 2
<class 'int'>
<class 'float'>


## 📝 Task 2 — Boolean Logic

### Background
Python's Boolean type has two values: `True` and `False`. Logical operators are written as English words: `and`, `or`, `not`. The XOR (exclusive or) result can be checked with `!=`.

### 🎯 Your Task
Given `p = True` and `q = False`:

1. Print the result of `p and q`, `p or q`, `not p`, and `p != q`
2. Create a variable `score = 73` and write an `if / elif / else` block that prints:
   - `"Distinction"` if score ≥ 85
   - `"Merit"` if score is between 70 and 84 (inclusive)
   - `"Pass"` if score is between 50 and 69 (inclusive)
   - `"Fail"` otherwise

> 💡 **Hint:** Use `elif` for multiple conditions. The order matters — check the highest threshold first.


In [18]:
p = True
q = False

# YOUR CODE HERE — Part 1: Boolean operations
#1. Print the result of `p and q`, `p or q`, `not p`, and `p != q`
print("p and q=", p and q)
print("p or q=", p or q)
print("not p=", not p)
print("p != q=", p != q)


# YOUR CODE HERE — Part 2: Grade classifier
score = 73
if score >= 85:
    print("Grade: A")
elif score >= 70 and score < 85:
    print("Grade: Merit")
elif score >= 50 and score < 69:
    print("Grade: Pass")
else:
    print("Grade: Fail")

p and q= False
p or q= True
not p= False
p != q= True
Grade: Merit


## 📝 Task 3 — String Operations

### Background
Strings in Python are sequences of characters. Useful built-in string methods include `.upper()`, `.lower()`, `.replace()`, `.split()`, `.strip()`, and `.count()`. You can also use `len()`, slicing `[start:end]`, and f-strings for formatting.

### 🎯 Your Task
Work with the sentence below and complete all five operations:

```python
sentence = "  Python is a powerful programming language  "
```

| # | Operation | Expected Result |
|---|-----------|-----------------|
| 1 | Strip whitespace | `"Python is a powerful programming language"` |
| 2 | Convert to UPPERCASE | `"PYTHON IS A POWERFUL PROGRAMMING LANGUAGE"` |
| 3 | Count the word `"a"` (exact, case-sensitive) | `1` |
| 4 | Replace `"powerful"` with `"versatile"` | `"Python is a versatile programming language"` |
| 5 | Split into a list of words | `['Python', 'is', 'a', 'versatile', ...]` |

Finally, use an **f-string** to print: `"The sentence has X words."` (where X is the actual count).

> 💡 **Hint:** Chain methods: `sentence.strip().upper()`. Use `.split()` with no arguments to split on any whitespace.


In [17]:
sentence = "  Python is a powerful programming language  "

# YOUR CODE HERE
# 1. Strip whitespace and save to 'clean'
clean = sentence.strip()
print("Cleaned sentence:", clean)
# 2. Print UPPERCASE version
print("Uppercase sentence:", clean.upper())

# 3. Count occurrences of the word "a"
count_a = clean.count("a")
print("Occurrences of 'a':", count_a)

# 4. Replace "powerful" with "versatile" and save to 'new_sentence'
new_sentence = clean.replace("powerful", "versatile")
print("New sentence:", new_sentence)

# 5. Split new_sentence into a list of words
split = new_sentence.split()
# Print: "The sentence has X words."

# num_words = len(split)
# print(f"The sentence has {num_words} words.")
print(f"The sentence has {len(split)} words.")

Cleaned sentence: Python is a powerful programming language
Uppercase sentence: PYTHON IS A POWERFUL PROGRAMMING LANGUAGE
Occurrences of 'a': 4
New sentence: Python is a versatile programming language
The sentence has 6 words.


## 📝 Task 4 — Loops & Conditionals

### Background
`for` loops iterate over a sequence. `while` loops run as long as a condition is `True`. Use `break` to exit early and `continue` to skip to the next iteration.

### 🎯 Your Task

**Part A:** Use a `for` loop with `range()` to print all **even numbers from 1 to 30** on a single line separated by spaces.

**Part B:** Use a `while` loop to compute the **sum of all odd numbers from 1 to 99** (i.e., 1 + 3 + 5 + … + 99). Print the result.
> Expected answer: 2500

**Part C:** Use a `for` loop over `range(1, 21)`. Print the number normally, **but**:
- If divisible by both 3 and 5 → print `"FizzBuzz"`
- If divisible by 3 only → print `"Fizz"`
- If divisible by 5 only → print `"Buzz"`

> 💡 **Hint for Part A:** Use `print(n, end=' ')` to stay on the same line, or build a list and use `' '.join(...)`.  
> 💡 **Hint for Part C:** Check the combined condition (`% 3 == 0 and % 5 == 0`) **first** before the individual ones.


In [33]:
# Part A: Even numbers from 1 to 30
# YOUR CODE HERE
for i in range(1, 31):
    if i % 2==0:
      print(i)

# Part B: Sum of odd numbers from 1 to 99
# YOUR CODE HERE
total = 0
for i in range(1, 100):
    if i % 2 != 0:    
        total += i  
print("Sum of odd numbers from 1 to 99:", total)


# Part C: FizzBuzz from 1 to 20
# YOUR CODE HERE
for i in range(1, 21):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)



2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
Sum of odd numbers from 1 to 99: 2500
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


---
# 📋 Section 2 — Lists


## 📝 Task 5 — List Basics: Create, Access, Modify

### Background
A Python list is **mutable** and **ordered**. Elements are accessed by zero-based index. Negative indices count from the end (`-1` is the last element). Common methods: `.append()`, `.insert()`, `.remove()`, `.pop()`, `.sort()`, `.reverse()`.

### 🎯 Your Task
Start with:
```python
fruits = ["mango", "banana", "apple", "cherry", "orange"]
```

Perform the following operations **in order**, printing the list after each step:

1. Print the **first** and **last** element using positive and negative indexing.
2. **Append** `"grape"` to the end.
3. **Insert** `"kiwi"` at index 2.
4. **Remove** `"banana"` from the list.
5. **Pop** the element at index 0 and print what was removed.
6. **Sort** the list alphabetically and print it.
7. **Reverse** the sorted list and print it.

> 💡 **Hint:** Remember that `.pop(index)` returns the removed element, so you can capture it: `removed = fruits.pop(0)`.


In [19]:
fruits = ["mango", "banana", "apple", "cherry", "orange"]

# YOUR CODE HERE
# 1. Print first and last elements
print(fruits[0], fruits[4])

# 2. Append "grape"
fruits.append("grape")
print(fruits)

# 3. Insert "kiwi" at index 2

fruits.insert(2,'kiwi')
print(fruits)
# 4. Remove "banana"
fruits.remove("banana")
print(fruits)   


# 5. Pop element at index 0, print what was removed ; pop return the removed element 
removed_element = fruits.pop(0)
print("Removed element:", removed_element)

# 6. Sort alphabetically
fruits.sort()
print(fruits)

# 7. Reverse the list
fruits.reverse()
print(fruits)


mango orange
['mango', 'banana', 'apple', 'cherry', 'orange', 'grape']
['mango', 'banana', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
['mango', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
Removed element: mango
['apple', 'cherry', 'grape', 'kiwi', 'orange']
['orange', 'kiwi', 'grape', 'cherry', 'apple']


## 📝 Task 6 — List Slicing

### Background
Slicing extracts a **sub-list** using the syntax `list[start:stop:step]`:
- `start` is inclusive, `stop` is exclusive
- A negative `step` reverses the direction
- Omitting `start` or `stop` defaults to the beginning or end

### 🎯 Your Task
Work with:
```python
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

| # | Slice | Expected Result |
|---|-------|-----------------|
| 1 | First 4 elements | `[0, 1, 2, 3]` |
| 2 | Last 3 elements | `[7, 8, 9]` |
| 3 | Elements from index 2 to 7 | `[2, 3, 4, 5, 6]` |
| 4 | Every second element | `[0, 2, 4, 6, 8]` |
| 5 | The entire list **reversed** | `[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]` |
| 6 | Last 5 elements **reversed** | `[9, 8, 7, 6, 5]` |

> 💡 **Hint:** To reverse use `[::-1]`. For last N items use `[-N:]`. To reverse a slice: `numbers[4:9][::-1]` reverses a sub-section.


In [56]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# YOUR CODE HERE
# 1. First 4 elements
print(numbers[0:4])

# 2. Last 3 elements

print(numbers[7:10])
# 3. Index 2 to 7 (not including 7)
print(numbers[2:7])

# 4. Every second element
print(numbers[0:10:2])

# 5. Entire list reversed
print(numbers[::-1])

# 6. Last 5 elements reversed
print(numbers[5:10][::-1])

[0, 1, 2, 3]
[7, 8, 9]
[2, 3, 4, 5, 6]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9, 8, 7, 6, 5]


## 📝 Task 7 — List Comprehensions

### Background
List comprehensions are a concise way to create lists:
```python
[expression for item in iterable if condition]
```
They replace many `for` loops with a single readable line.

### 🎯 Your Task
Use **list comprehensions** (no regular for-loops!) to create and print each of the following:

1. A list of the **squares** of numbers 1 through 15: `[1, 4, 9, 16, ...]`
2. A list of numbers from 1–50 that are **divisible by 3 or 5** (but not both): `[3, 5, 6, 9, 10, ...]`
3. A list of the **lengths** of each word in the sentence `"the quick brown fox jumps over the lazy dog"`
4. A list of **uppercase versions** of only the words that have **5 or more letters**: `['QUICK', 'BROWN', 'JUMPS', 'LAZY']` *(hint: 'over' has 4, skip it)*

> 💡 **Hint for #2:** `(n % 3 == 0) != (n % 5 == 0)` is Python's way to express XOR for two conditions.  
> 💡 **Hint for #3:** `sentence.split()` gives you the word list.


In [21]:
# 1. Squares of 1 to 15
# YOUR CODE HERE

for i in range(0,16):
    print(i**2)

# 2. Numbers 1-50 divisible by 3 OR 5 but NOT both
# YOUR CODE HERE

for i in range(1, 51):
    if (i % 3 == 0 or i % 5 == 0) and not (i % 3 == 0 and i % 5 == 0):
        print(i)    

# 3. Lengths of each word in the sentence
sentence = "the quick brown fox jumps over the lazy dog"
# YOUR CODE HERE
words = sentence.split()
# 4. Uppercase words with 5 or more letters
# YOUR CODE HERe
lengths=[len(word) for word in words]
print('Lengths of words;' , lengths)
# 4. Uppercase words with 5 or more letters
for word in words:
    if len(word) >= 5:
        print(word.upper())


0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
3
5
6
9
10
12
18
20
21
24
25
27
33
35
36
39
40
42
48
50
Lengths of words; [3, 5, 5, 3, 5, 4, 3, 4, 3]
QUICK
BROWN
JUMPS


## 📝 Task 8 — Nested Lists & the `collections.Counter`

### Background
A **list of lists** creates a 2D (matrix-like) structure. Access elements with `matrix[row][col]`.  
`collections.Counter` is a dictionary subclass that counts how many times each element appears in an iterable.

### 🎯 Your Task

**Part A — Nested List:**  
Create the following 3×3 matrix as a list of lists and then:
```
matrix = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
```
- Print the **second row** (index 1)
- Print the **element at row 2, column 1** (value: 8)
- Use a nested list comprehension to create a **transposed** version (rows become columns)
  - Expected: `[[1, 4, 7], [2, 5, 8], [3, 6, 9]]`

**Part B — Counter:**  
Generate a list of 300 random integers between 1 and 10 (inclusive), then:
- Use `collections.Counter` to count each number
- Print the **3 most common** numbers and their counts
- Print the **least common** number

> 💡 **Hint for transpose:** `[[matrix[r][c] for r in range(3)] for c in range(3)]`  
> 💡 **Hint for Counter:** `counter.most_common(3)` returns the top 3 as a list of `(value, count)` tuples.


In [23]:
import collections, random

# Part A — Nested list
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# YOUR CODE HERE
# Print second row
print(matrix[1])

# Print element at row 2, col 1
print(matrix[0][1])

# Transpose using nested list comprehension
# 3. Transpose using nested list comprehension
transpose = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print("Transposed matrix:")
for row in transpose:
    print(row)

# Part B — Counter
random.seed(42)
# YOUR CODE HERE
# Generate 300 random integers between 1 and 10
number=[random.randint(1,10) for _ in range(300)]
print(number)

# Count with Counter
counter=collections.Counter(number)

# Print top 3 most common
print(counter.most_common(3))
# Print least common
min_count=min(counter.values())
least_common = [num for num, count in counter.items() if count == min_count]    
print("Least common numbers:", least_common)

[4, 5, 6]
2
Transposed matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]
[2, 1, 5, 4, 4, 3, 2, 9, 2, 10, 7, 1, 1, 2, 4, 4, 9, 10, 1, 9, 4, 9, 7, 4, 8, 10, 5, 1, 3, 7, 6, 5, 3, 4, 6, 2, 2, 7, 2, 6, 6, 10, 5, 1, 8, 9, 2, 7, 2, 9, 5, 10, 6, 10, 4, 2, 1, 4, 5, 2, 4, 2, 7, 5, 8, 6, 3, 6, 6, 4, 5, 2, 10, 3, 9, 4, 3, 8, 7, 5, 9, 4, 6, 1, 4, 1, 6, 7, 5, 2, 4, 10, 6, 4, 8, 7, 8, 3, 5, 3, 4, 9, 9, 5, 10, 7, 10, 7, 6, 4, 3, 9, 8, 2, 1, 2, 3, 3, 7, 10, 2, 7, 7, 10, 8, 9, 5, 9, 1, 2, 9, 5, 6, 2, 5, 7, 3, 8, 1, 5, 9, 3, 9, 2, 5, 9, 10, 4, 3, 6, 3, 9, 9, 1, 10, 6, 8, 1, 2, 6, 5, 4, 1, 4, 10, 2, 2, 8, 2, 9, 3, 3, 8, 9, 3, 5, 9, 10, 7, 4, 9, 4, 5, 7, 6, 8, 9, 8, 2, 4, 4, 2, 6, 1, 10, 9, 4, 10, 4, 1, 2, 1, 4, 2, 1, 6, 2, 9, 4, 5, 8, 4, 9, 3, 10, 10, 8, 4, 8, 7, 4, 2, 2, 7, 6, 7, 7, 8, 1, 2, 1, 7, 6, 2, 4, 4, 4, 9, 8, 3, 7, 3, 5, 8, 4, 2, 8, 9, 2, 1, 9, 1, 2, 4, 3, 7, 8, 8, 4, 7, 1, 3, 7, 1, 7, 5, 8, 5, 7, 9, 8, 3, 4, 5, 4, 1, 10, 9, 1, 6, 1, 1, 10, 8, 9, 9, 3, 1, 9, 2, 3, 2, 10, 2, 4, 7, 2, 10, 4, 10]
[(4, 42), (2,

---
# 🔒 Section 3 — Tuples


## 📝 Task 9 — Tuples: Immutability & Practical Uses

### Background
Tuples look like lists but use `()` instead of `[]`. They are **immutable** — you cannot add, remove, or change elements after creation. This makes them useful for fixed data like coordinates, RGB colours, or records. Tuples support indexing, slicing, and iteration just like lists.

### 🎯 Your Task

**Part A — Basic Tuple Operations:**
```python
student = ("Alice", 22, "Computer Science", 3.8)
```
- Print the student's name (index 0) and GPA (index 3)
- Try to change the name to `"Bob"` — catch the resulting `TypeError` with a `try/except` block and print `"Tuples are immutable!"`
- Unpack the tuple into 4 separate variables: `name, age, major, gpa` and print each

**Part B — List of Tuples:**  
You have coordinates of 5 cities:
```python
cities = [("Karachi", 24.86, 67.01),
          ("Lahore",  31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar", 34.01, 71.57),
          ("Quetta",  30.18, 66.99)]
```
- Loop over the list and print each city in the format: `"City: Karachi | Lat: 24.86 | Lon: 67.01"`
- Sort the cities by **latitude** (ascending) and print the sorted list

> 💡 **Hint for sorting:** `sorted(cities, key=lambda c: c[1])` sorts by the second element of each tuple.


In [1]:
# Part A
student = ("Alice", 22, "Computer Science", 3.8)

# YOUR CODE HERE
# Print name and GPA
print(f"Name: {student[0]}, CGPA: {student[3]}")

# Try to change name — catch TypeError
try:
    student[0] = "Bob"
except TypeError as e:
    print("Error:", e)      

# Unpack into 4 variables and print each
name, age, major, gpa = student

print("Name:", name)
print("Age:", age)
print("Major:", major)
print("GPA:", gpa)

# Part B
cities = [("Karachi",   24.86, 67.01),
          ("Lahore",    31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar",  34.01, 71.57),
          ("Quetta",    30.18, 66.99)]

# YOUR CODE HERE
# Loop and print each city's info
for city in cities: 
    name, lat, lon = city
    print(f"City: {name}, Latitude: {lat}, Longitude: {lon}")   

# Sort by latitude and print
cities.sort(key=lambda x: x[1])  # Sort by latitude (index 1)
print("\nCities sorted by latitude:")
for city in cities:         
    name, lat, lon = city
    print(f"City: {name}, Latitude: {lat}, Longitude: {lon}")       

        

Name: Alice, CGPA: 3.8
Error: 'tuple' object does not support item assignment
Name: Alice
Age: 22
Major: Computer Science
GPA: 3.8
City: Karachi, Latitude: 24.86, Longitude: 67.01
City: Lahore, Latitude: 31.55, Longitude: 74.35
City: Islamabad, Latitude: 33.72, Longitude: 73.06
City: Peshawar, Latitude: 34.01, Longitude: 71.57
City: Quetta, Latitude: 30.18, Longitude: 66.99

Cities sorted by latitude:
City: Karachi, Latitude: 24.86, Longitude: 67.01
City: Quetta, Latitude: 30.18, Longitude: 66.99
City: Lahore, Latitude: 31.55, Longitude: 74.35
City: Islamabad, Latitude: 33.72, Longitude: 73.06
City: Peshawar, Latitude: 34.01, Longitude: 71.57


---
# 📖 Section 4 — Dictionaries


## 📝 Task 10 — Dictionary Basics: Create, Access, Update

### Background
A dictionary stores data as **key → value** pairs. Keys must be unique and immutable (strings, numbers, tuples). Values can be anything. Key methods: `.keys()`, `.values()`, `.items()`, `.get()`, `.update()`, `.pop()`.

### 🎯 Your Task
Start with this student record:
```python
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}
```

1. Print Sara's **name** and **age**
2. Print her **list of courses**
3. Print her **CS grade** (access the nested dictionary)
4. Add a new key `"year"` with value `2`
5. Update her **age** to `21`
6. Remove the `"Physics"` grade from the nested `"grades"` dictionary using `.pop()`
7. Loop over all key-value pairs with `.items()` and print them line by line
8. Print a list of all **keys** and a list of all **values**

> 💡 **Hint:** Access nested dicts with chained brackets: `student["grades"]["CS"]`  
> 💡 **Hint:** `student.get("email", "Not found")` returns a default value if the key doesn't exist.


In [2]:
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}

# YOUR CODE HERE
# 1. Print name and age
print("Name:", student["name"])
print("Age:", student["age"])

# 2. Print list of courses
print("Courses:", student["courses"])

# 3. Print CS grade (nested access)
print("CS Grade:", student["grades"]["CS"])

# 4. Add "year": 2
student["year"] = 2

# 5. Update age to 21
student["year"] = 2

# 6. Remove "Physics" from grades using .pop()
removed_grade = student["grades"].pop("Physics")
print("Removed Physics grade:", removed_grade)
# 7. Loop and print all key-value pairs
print("\nStudent information:")
for key, value in student.items():
    print(key, ":", value)

# 8. Print list of keys and list of values
print("\nKeys:", list(student.keys()))
print("Values:", list(student.values()))

Name: Sara
Age: 20
Courses: ['Math', 'Physics', 'CS']
CS Grade: 92
Removed Physics grade: 75

Student information:
name : Sara
age : 20
courses : ['Math', 'Physics', 'CS']
grades : {'Math': 88, 'CS': 92}
year : 2

Keys: ['name', 'age', 'courses', 'grades', 'year']
Values: ['Sara', 20, ['Math', 'Physics', 'CS'], {'Math': 88, 'CS': 92}, 2]


## 📝 Task 11 — Dictionary Comprehension & Word Frequency Counter

### Background
Just like list comprehensions, you can build dictionaries in one line:
```python
{key_expr: value_expr for item in iterable if condition}
```
Dictionaries are perfect for counting frequencies — a pattern you'll use constantly in data science.

### 🎯 Your Task

**Part A — Dictionary Comprehension:**
1. Create a dictionary mapping each number 1–10 to its **cube**: `{1: 1, 2: 8, 3: 27, ...}`
2. Create a dictionary mapping each number 1–20 to `"even"` or `"odd"`: `{1: 'odd', 2: 'even', ...}`

**Part B — Word Frequency Counter:**  
Count how many times each word appears in the text below, ignoring case. Print the result sorted by **frequency (descending)**.

```python
text = "to be or not to be that is the question to be is to think"
```
Expected top entries: `to: 4, be: 3, is: 2, ...`

> 💡 **Hint for Part B:** Start with `freq = {}`, then loop over `text.lower().split()`.  
> Use `freq[word] = freq.get(word, 0) + 1` to safely increment counts.  
> Sort with `sorted(freq.items(), key=lambda x: x[1], reverse=True)`.


In [3]:
# Part A — Dictionary comprehensions
# 1. Cubes of 1 to 10
# YOUR CODE HERE
for i in range(1,11):
    print(f"{i}: {i**3}")

# 2. Even/Odd mapping for 1 to 20
# YOUR CODE HERE
even_odd = {i: "even" if i % 2 == 0 else "odd" for i in range(1, 21)}
print(even_odd)

# Part B — Word frequency counter
text = "to be or not to be that is the question to be is to think"
# YOUR CODE HERE
words = text.split() 
word_freq = {word: words.count(word) for word in set(words)}
print(word_freq)

1: 1
2: 8
3: 27
4: 64
5: 125
6: 216
7: 343
8: 512
9: 729
10: 1000
{1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd', 6: 'even', 7: 'odd', 8: 'even', 9: 'odd', 10: 'even', 11: 'odd', 12: 'even', 13: 'odd', 14: 'even', 15: 'odd', 16: 'even', 17: 'odd', 18: 'even', 19: 'odd', 20: 'even'}
{'the': 1, 'that': 1, 'not': 1, 'or': 1, 'to': 4, 'be': 3, 'think': 1, 'question': 1, 'is': 2}


---
# 🔵 Section 5 — Sets


## 📝 Task 12 — Set Operations

### Background
A **set** is an **unordered collection of unique elements**. Duplicate values are automatically removed. Sets support mathematical operations: union (`|`), intersection (`&`), difference (`-`), symmetric difference (`^`).

| Operation | Symbol | Method | Meaning |
|-----------|--------|--------|---------|
| Union | `\|` | `.union()` | All elements from both sets |
| Intersection | `&` | `.intersection()` | Only elements in **both** |
| Difference | `-` | `.difference()` | Elements in A but **not** B |
| Symmetric Difference | `^` | `.symmetric_difference()` | Elements in either but **not both** |

### 🎯 Your Task
```python
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
```

1. Find students enrolled in **both** courses (intersection)
2. Find students enrolled in **at least one** course (union)
3. Find students taking **Python but NOT Java** (difference)
4. Find students taking **exactly one** course (symmetric difference)
5. Check if `{"Bob", "Alice"}` is a **subset** of `python_students`
6. Add `"Henry"` to `python_students` and remove `"Carol"` from it
7. Create a list `[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]` and use a set to print only the **unique values**

> 💡 **Hint:** Use `.issubset()` or the `<=` operator for subset check.


In [4]:
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}

# YOUR CODE HERE
# 1. Intersection
print("Intersection:", python_students.intersection(java_students))

# 2. Union
print("Union:", python_students.union(java_students))

# 3. Difference (Python but NOT Java)
print("Python only:", python_students.difference(java_students))

# 4. Symmetric difference
print("Symmetric difference:", python_students.symmetric_difference(java_students))

# 5. Subset check: {"Bob", "Alice"} ⊆ python_students
print("Is subset:", {"Bob", "Alice"}.issubset(python_students))


# 6. Add "Henry", remove "Carol"
python_students.add("Henry")
python_students.remove("Carol")
print("Updated python students:", python_students)

# 7. Unique values from list
nums = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
unique_nums = set(nums)
print("Unique numbers:", unique_nums)


Intersection: {'Bob', 'David', 'Alice'}
Union: {'Eve', 'Carol', 'Grace', 'Bob', 'David', 'Frank', 'Alice'}
Python only: {'Eve', 'Carol'}
Symmetric difference: {'Grace', 'Eve', 'Carol', 'Frank'}
Is subset: True
Updated python students: {'Henry', 'Eve', 'Bob', 'David', 'Alice'}
Unique numbers: {1, 2, 3, 4}


---
# 🔢 Section 6 — NumPy Arrays


## 📝 Task 13 — Creating & Inspecting NumPy Arrays

### Background
NumPy arrays are **fixed-type, multi-dimensional** arrays that support fast vectorised operations. Unlike Python lists, every element must be the same type. Key creation functions: `np.array()`, `np.arange()`, `np.linspace()`, `np.zeros()`, `np.ones()`, `np.eye()`, `np.random.random()`.

### 🎯 Your Task

Create each of the following arrays and print both the array and its `.shape` and `.dtype`:

| # | Function | Parameters | Expected shape |
|---|----------|------------|----------------|
| 1 | `np.arange` | 0 to 20, step 2 | `(11,)` |
| 2 | `np.linspace` | 0 to 1, 6 evenly spaced points | `(6,)` |
| 3 | `np.zeros` | 3 rows × 4 columns | `(3, 4)` |
| 4 | `np.ones` | 2 rows × 5 columns, dtype `int16` | `(2, 5)` |
| 5 | `np.eye` | 4×4 identity matrix | `(4, 4)` |
| 6 | `np.random.randint` | values 1–100, shape 3×3 | `(3, 3)` |

> 💡 **Hint:** `np.ones((2,5), dtype='int16')` creates an integer array of ones.  
> `np.random.randint(low, high, size=(r,c))` creates random integer arrays.


In [5]:
import numpy as np

# YOUR CODE HERE
# 1. arange: 0 to 20 step 2
arr1 = np.arange(0, 21, 2)
print("arange:", arr1)

# 2. linspace: 0 to 1 with 6 points
arr2 = np.linspace(0, 1, 6)
print("linspace:", arr2)

# 3. zeros: 3x4
arr3 = np.zeros((3, 4))
print("zeros:\n", arr3) 

# 4. ones: 2x5 dtype int16
arr4 = np.ones((2, 5), dtype=np.int16)
print("ones:\n", arr4)

# 5. eye: 4x4 identity
arr5 = np.eye(4)
print("eye:\n", arr5)   

# 6. random integers 1-100, shape 3x3
arr6 = np.random.randint(1, 101, size=(3, 3))
print("Random integers:\n", arr6)

arange: [ 0  2  4  6  8 10 12 14 16 18 20]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]
zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
eye:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random integers:
 [[22 82 65]
 [ 3  9 46]
 [76 61 80]]


## 📝 Task 14 — Array Indexing, Slicing & Reshaping

### Background
NumPy arrays use **row, column** indexing: `A[row, col]` or `A[row][col]`.  
Slicing: `A[r1:r2, c1:c2]` extracts a sub-array.  
`.reshape(rows, cols)` changes the shape without changing the data.  
`.T` gives the transpose.

### 🎯 Your Task
```python
A = np.arange(1, 26).reshape(5, 5)
```
This creates:
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
```

1. Print the **element at row 2, column 3** (value: 14)
2. Print the **entire third row** (index 2): `[11 12 13 14 15]`
3. Print the **entire second column** (index 1): `[ 2  7 12 17 22]`
4. Extract the **top-left 3×3 sub-matrix**: rows 0–2, columns 0–2
5. Extract the **bottom-right 2×2 sub-matrix**: last 2 rows and last 2 cols
6. Print the **transpose** of A (shape should become `(5,5)` but rows/cols swapped)
7. Reshape A into a 1D array of 25 elements, then into a shape `(25, 1)` column vector

> 💡 **Hint:** `A[:3, :3]` extracts the top-left corner. `A[-2:, -2:]` grabs the bottom-right corner.


In [ ]:
c

## 📝 Task 15 — Vectorised Operations & Broadcasting

### Background
NumPy operations are applied **element-wise** to entire arrays without writing loops — this is called **vectorisation**. When arrays have compatible shapes, NumPy can **broadcast** smaller arrays across larger ones automatically.

### 🎯 Your Task

**Part A — Element-wise Operations:**
```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])
```
Compute and print (without loops):
1. `a + b`, `a - b`, `a * b`, `a / b`
2. Square root of `a` (use `np.sqrt`)
3. All elements of `a` greater than 25 (Boolean mask)
4. Use the Boolean mask to extract only elements of `a` greater than 25

**Part B — Matrix Operations:**
```python
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
```
5. Element-wise multiplication `M * N`
6. Matrix (dot) product `M @ N` or `np.dot(M, N)`
7. Sum of all elements, sum along each row, sum along each column

> 💡 **Hint for Boolean masking:** `mask = a > 25` creates `[False False False True True]`. Then `a[mask]` extracts `[40 50]`.  
> 💡 **Hint for axis sums:** `M.sum(axis=1)` sums each row; `M.sum(axis=0)` sums each column.


In [6]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])

# Part A
# YOUR CODE HERE
# 1. Element-wise +, -, *, /
# 1. Element-wise +, -, *, /
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# 2. Square root of a
print("Square root of a:", np.sqrt(a))

# 3. Boolean mask: elements of a > 25
mask = a > 25
print("Boolean mask:", mask)

# 4. Extract elements > 25 using mask
print("Elements greater than 25:", a[mask])


# Part B
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])

# YOUR CODE HERE
# 5. Element-wise multiplication
print("Element-wise multiplication:\n", M * N)

# 6. Matrix dot product
print("Matrix dot product:\n", np.dot(M, N))

# 7. Total sum, row sums, column sums

print("Total sum:", np.sum(M))
print("Row sums:", np.sum(M, axis=1))
print("Column sums:", np.sum(M, axis=0))

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Square root of a: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Boolean mask: [False False  True  True  True]
Elements greater than 25: [30 40 50]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix dot product:
 [[19 22]
 [43 50]]
Total sum: 10
Row sums: [3 7]
Column sums: [4 6]


---
# 🐼 Section 7 — Pandas DataFrames


## 📝 Task 16 — Creating & Exploring a DataFrame

### Background
A **DataFrame** is a 2D table with labelled rows (index) and columns. You can create one from a dictionary, a list of lists, a CSV file, or from scikit-learn datasets. Essential inspection methods: `.head()`, `.tail()`, `.info()`, `.describe()`, `.shape`, `.columns`, `.dtypes`, `.isnull().sum()`.

### 🎯 Your Task

**Part A — Create from a dictionary:**
```python
data = {
    "Name":    ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":     [23, 21, 25, 22, 24],
    "Score":   [88, 92, 78, 95, 83],
    "Passed":  [True, True, True, True, True],
    "City":    ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
```
1. Create a DataFrame from this dictionary
2. Print its **shape**, **column names**, and **data types**
3. Print the **first 3 rows** and the **last 2 rows**
4. Print **summary statistics** using `.describe()`

**Part B — Load the Iris dataset:**
5. Load the Iris dataset using `load_iris()` and add the species names
6. Print **how many rows belong to each species** using `.value_counts()`
7. Print the **mean of each numerical column grouped by species**

> 💡 **Hint for Iris:** `iris_df['species'] = iris.target_names[iris.target]` maps integer targets to names.  
> 💡 **Hint for groupby:** `iris_df.groupby('species').mean(numeric_only=True)`


In [13]:
import pandas as pd
from sklearn.datasets import load_iris

# Part A
data = {
    "Name":   ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":    [23, 21, 25, 22, 24],
    "Score":  [88, 92, 78, 95, 83],
    "Passed": [True, True, True, True, True],
    "City":   ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}

# YOUR CODE HERE
# 1. Create DataFrame
df = pd.DataFrame(data)
print(df)

# 2. Print shape, columns, dtypes
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Dtypes:")
print(df.dtypes)

# 3. Head(3) and tail(2)
print("\nFirst 3 rows:\n", df.head(3))
print("\nLast 2 rows:\n", df.tail(2))

# 4. Describe
print("\nDescribe:\n", df.describe())

# Part B — Iris
# YOUR CODE HERE
# 5. Load iris and create DataFrame
iris = load_iris()
iris_df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

iris_df["species"] = iris.target

print("\nIris DataFrame:\n", iris_df.head())
# 6. Value counts per species

print("\nValue counts per species:\n", iris_df["species"].value_counts())

# 7. Mean per species
print("\nMean per species:\n", iris_df.groupby("species").mean())

     Name  Age  Score  Passed       City
0     Ali   23     88    True     Lahore
1    Sara   21     92    True    Karachi
2    John   25     78    True     London
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York
Shape: (5, 5)
Columns: ['Name', 'Age', 'Score', 'Passed', 'City']
Dtypes:
Name        str
Age       int64
Score     int64
Passed     bool
City        str
dtype: object

First 3 rows:
    Name  Age  Score  Passed     City
0   Ali   23     88    True   Lahore
1  Sara   21     92    True  Karachi
2  John   25     78    True   London

Last 2 rows:
      Name  Age  Score  Passed       City
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York

Describe:
              Age     Score
count   5.000000   5.00000
mean   23.000000  87.20000
std     1.581139   6.83374
min    21.000000  78.00000
25%    22.000000  83.00000
50%    23.000000  88.00000
75%    24.000000  92.00000
max    25.000000  95.00000

Iris DataFrame:
    sepal le

## 📝 Task 17 — Selecting, Filtering & Adding Columns

### Background
- **Select columns:** `df['col']` (Series) or `df[['col1','col2']]` (DataFrame)
- **Select rows by position:** `df.iloc[start:stop]`
- **Select rows by label/condition:** `df.loc[condition]`
- **Add a column:** `df['new_col'] = expression`
- **Multiple conditions:** Use `&` (AND) or `|` (OR) — wrap each condition in `()`

### 🎯 Your Task
Use the **Iris DataFrame** from Task 16.

1. Select and print only the `sepal length (cm)` and `petal length (cm)` columns (first 5 rows)
2. Select rows **50 through 54** using `.iloc`
3. Filter rows where `species == 'versicolor'` and print how many there are
4. Filter rows where `petal length (cm) > 5.0` **AND** `species == 'virginica'`
5. Add a new column `"petal_area"` = `petal length (cm)` × `petal width (cm)` and print the first 5 rows
6. Sort the DataFrame by `petal_area` in **descending** order and print the top 5 rows

> 💡 **Hint:** `df[(df['col1'] > val) & (df['col2'] == 'label')]` — always wrap each condition in `()`.  
> 💡 **Hint:** `df.sort_values('petal_area', ascending=False).head(5)`


In [14]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

# YOUR CODE HERE
# 1. Select sepal length and petal length columns (head 5)
print(iris_df[['sepal length (cm)', 'petal length (cm)']].head())


# 2. Rows 50 through 54 using iloc
print(iris_df.iloc[50:55])

# 3. Filter versicolor species, print count
versicolor = iris_df[iris_df['species'] == 'versicolor']
print("Versicolor count:", versicolor.shape[0])


# 4. Filter: petal length > 5.0 AND species == 'virginica'
filtered = iris_df[
    (iris_df['petal length (cm)'] > 5.0) &
    (iris_df['species'] == 'virginica')
]
print(filtered)


# 5. Add petal_area column, print head
filtered = iris_df[
    (iris_df['petal length (cm)'] > 5.0) &
    (iris_df['species'] == 'virginica')
]
print(filtered)


# 6. Sort by petal_area descending, top 5
filtered = iris_df[
    (iris_df['petal length (cm)'] > 5.0) &
    (iris_df['species'] == 'virginica')
]
print(filtered)


   sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

       species  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
54  versicolor  
Versicolor count: 50
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
100                6.3               3.3                6.0               2

## 📝 Task 18 — Capstone: Combined Data Structures Challenge

### Background
Real data science tasks require combining **all** the data structures you have learned. This final task tests your ability to choose the right structure for each job.

### 🎯 Your Task
You are given student records as a **list of dictionaries**:

```python
students = [
    {"name": "Alice",   "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",     "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",   "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",   "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",     "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",   "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",   "scores": [75, 80, 78], "city": "Lahore"},
]
```

Complete each of the following:

1. **Average score:** Add a key `"average"` to each student dict containing the average of their `scores` (round to 2 decimal places). Print all names and averages.

2. **Grade assignment:** Using a dictionary comprehension, create a dict `{name: grade}` where grade is:
   - `"A"` if average ≥ 85
   - `"B"` if average ≥ 70
   - `"C"` if average ≥ 55
   - `"F"` otherwise

3. **Top students:** Use a list comprehension to create a list of **names** of students with average ≥ 80.

4. **Unique cities:** Use a **set** to find all unique cities, then print them.

5. **NumPy statistics:** Convert all scores into a **2D NumPy array** (shape `7×3`). Compute and print:
   - Overall mean, min, max
   - Mean score per student (axis=1)
   - Mean score per test/column (axis=0)

6. **Pandas summary:** Create a **DataFrame** with columns `Name`, `Average`, `Grade`, `City`. Print it, then print the **average score per city** using `.groupby()`.

> 💡 **Hints:**
> - `sum(scores) / len(scores)` or `np.mean(scores)` for averages
> - `np.array([s["scores"] for s in students])` to build the 2D array
> - For the DataFrame, build a list of dicts or use parallel lists


In [15]:
import numpy as np
import pandas as pd

students = [
    {"name": "Alice",  "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",    "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",  "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",  "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",    "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",  "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",  "scores": [75, 80, 78], "city": "Lahore"},
]

# YOUR CODE HERE — Step 1: Add "average" key to each student dict
for s in students:
    s["average"] = sum(s["scores"]) / len(s["scores"])

print("Students with averages:\n", students)

# YOUR CODE HERE — Step 2: Dict comprehension {name: grade}
grades = {
    s["name"]: (
        "A" if s["average"] >= 85 else
        "B" if s["average"] >= 70 else
        "C"
    )
    for s in students
}

print("\nGrades:", grades)


# YOUR CODE HERE — Step 3: List of names with average >= 80
top_students = [s["name"] for s in students if s["average"] >= 80]

print("\nStudents with average >= 80:", top_students)


# YOUR CODE HERE — Step 4: Set of unique cities
cities = {s["city"] for s in students}

print("\nUnique cities:", cities)

# YOUR CODE HERE — Step 5: NumPy 2D array and statistics
scores_array = np.array([s["scores"] for s in students])

print("\nScores Array:\n", scores_array)

print("\nMean per subject:", scores_array.mean(axis=0))
print("Mean per student:", scores_array.mean(axis=1))
print("Overall mean:", scores_array.mean())

# YOUR CODE HERE — Step 6: Pandas DataFrame and groupby city
df = pd.DataFrame(students)

print("\nDataFrame:\n", df)

city_avg = df.groupby("city")["average"].mean()

print("\nAverage score by city:\n", city_avg)

Students with averages:
 [{'name': 'Alice', 'scores': [85, 90, 78], 'city': 'Lahore', 'average': 84.33333333333333}, {'name': 'Bob', 'scores': [60, 55, 70], 'city': 'Karachi', 'average': 61.666666666666664}, {'name': 'Carol', 'scores': [92, 88, 95], 'city': 'Islamabad', 'average': 91.66666666666667}, {'name': 'David', 'scores': [70, 65, 80], 'city': 'Lahore', 'average': 71.66666666666667}, {'name': 'Eve', 'scores': [50, 45, 55], 'city': 'Karachi', 'average': 50.0}, {'name': 'Frank', 'scores': [88, 92, 84], 'city': 'Islamabad', 'average': 88.0}, {'name': 'Grace', 'scores': [75, 80, 78], 'city': 'Lahore', 'average': 77.66666666666667}]

Grades: {'Alice': 'B', 'Bob': 'C', 'Carol': 'A', 'David': 'B', 'Eve': 'C', 'Frank': 'A', 'Grace': 'B'}

Students with average >= 80: ['Alice', 'Carol', 'Frank']

Unique cities: {'Karachi', 'Lahore', 'Islamabad'}

Scores Array:
 [[85 90 78]
 [60 55 70]
 [92 88 95]
 [70 65 80]
 [50 45 55]
 [88 92 84]
 [75 80 78]]

Mean per subject: [74.28571429 73.57142857 

---
## 🤔 Reflection Questions

Answer the following as comments in the cell below:

1. What is the key difference between a **list** and a **tuple**? When would you prefer a tuple?
2. What is the key difference between a **list** and a **set**? Give one real-world use case for each.
3. Why can't a **list** be used as a dictionary key, but a **tuple** can?
4. In Task 15, what is the advantage of NumPy **vectorisation** over using a Python `for` loop?
5. In Task 17, why do we use `&` instead of `and` when filtering a Pandas DataFrame?
6. Looking at the Capstone (Task 18), which data structure did you find most useful? Why?


In [ ]:
# 1. What is the key difference between a list and a tuple? When would you prefer a tuple?
# A list is mutable (its elements can be changed), while a tuple is immutable (cannot be modified after creation).
# A tuple is preferred when the data should remain constant, such as coordinates, fixed records,
# or when using values as dictionary keys for better safety and performance.

# 2. What is the key difference between a list and a set? Give one real-world use case for each.
# A list is an ordered collection that allows duplicate values.
# A set is an unordered collection that does not allow duplicates.
# Example use cases:
# List: storing a sequence like daily temperatures or exam scores.
# Set: storing unique items like unique user IDs or unique website visitors.

# 3. Why can't a list be used as a dictionary key, but a tuple can?
# Dictionary keys must be hashable and immutable.
# Lists are mutable (they can change), so they are not hashable and cannot be dictionary keys.
# Tuples are immutable, so they are hashable and can safely be used as dictionary keys.

# 4. In Task 15, what is the advantage of NumPy vectorisation over using a Python for loop?
# NumPy vectorisation performs operations on entire arrays at once using optimized C code,
# making it much faster and more efficient than iterating through elements with a Python for loop.

# 5. In Task 17, why do we use & instead of and when filtering a Pandas DataFrame?
# '&' performs element-wise logical operations on Pandas Series or NumPy arrays.
# 'and' only works with single boolean values and cannot operate on entire columns.

# 6. Looking at the Capstone (Task 18), which data structure did you find most useful? Why?
# The Pandas DataFrame is the most useful because it organizes data in a tabular structure
# and provides powerful tools for filtering, grouping, statistical analysis, and data manipulation.