#### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

#### COPY:

In [2]:
!pip install numpy 

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 303.0 kB/s eta 0:00:40
   - -------------------------------------- 0.5/12.5 MB 303.0 kB/s eta 0:00:40
   - -------------------------------------- 0.5/12.5 MB 303.0 kB/s eta 0:00:40
   -- ------------------------------------- 0.8/12.5 MB 355.7 kB/s eta 0:00:33
   -- ------------------------------------- 0.8/12.5 M


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
#Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


#### VIEW:

In [4]:
#Make a view, change the original array, and display both arrays: 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


#### Make Changes in the VIEW: 

In [7]:
#Make a view, change the view, and display both arrays: 
import numpy as np

arr = np.array([11, 12, 13, 14, 15])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31 12 13 14 15]
[31 12 13 14 15]


#### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [8]:
#Print the value of the base attribute to check if an array owns it's data or not: 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
