Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

#### Generate Random Number
NumPy offers the random module to work with random numbers.

In [1]:
#Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

89


#### Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [2]:
#Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.5172969151492774


#### Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

#### Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [3]:
#Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

[17 80 98 57  0]


In [4]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[36 17 78 85 95]
 [61 94 95 54 86]
 [91  4 10 55 87]]


#### Floats
The rand() method also allows you to specify the shape of the array.

In [5]:
#Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x)

[0.87045854 0.61405549 0.55914887 0.18416176 0.81773603]


In [6]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:

from numpy import random

x = random.rand(3, 5)

print(x)

[[0.63769248 0.53092988 0.5366175  0.90251194 0.56405295]
 [0.15192154 0.61069781 0.23156674 0.31775102 0.54586474]
 [0.73670248 0.27809836 0.382601   0.76090826 0.08000571]]


#### Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [7]:
#Return one of the values in an array:

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [8]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)


[[7 5 7 5 7]
 [9 3 7 5 5]
 [9 9 9 7 3]]
